
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import pandas as pd
from main import *
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,ttk,IntVar

csv_file="budget_app/data.csv"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Kornel z devils.one\Desktop\vsc\budget_app\assets\frame0")
OPTIONS = ["Income", "Expenses", "Savings"]


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def calculate_balance():
    try:
        df = pd.read_csv(csv_file)
        balance =sum(df[df["operation"]=="Income"]["amount"]) - sum(df[df["operation"]=="Expenses"]["amount"])
        return balance

    except:
        return 0


def get_data():
    
    data = {
        "operation":combobox.get(),
        "name":entry_Name.get(),
        "amount":int(entry_amount.get()),
        "balance":calculate_balance()

        }
    print(data)

    
    try:
        df = pd.read_csv(csv_file)
    except FileNotFoundError :
    
        df = pd.DataFrame()

    new_data_df = pd.DataFrame([data])

    df = pd.concat([df, new_data_df], ignore_index=True)

    df.to_csv(csv_file, index=False)
    print("Data appended successfully to", csv_file)
    
###GUI
window = Tk()

df = pd.read_csv(csv_file)

window.geometry("700x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    42.0,
    image=image_image_1
)

canvas.create_text(
    28.0,
    7.0,
    anchor="nw",
    text="Budget Tracker",
    fill="#FFFFFF",
    font=("Inter Medium", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    177.0,
    130.0,
    image=image_image_2
)

income_id = canvas.create_text(
    82.0,
    116.0,
    anchor="nw",
    text=0,
    fill="#000000",
    font=("Inter Medium", 24 * -1)
)

canvas.create_text(
    82.0,
    102.0,
    anchor="nw",
    text="Income",
    fill="#000000",
    font=("Inter", 13 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    487.0,
    129.0,
    image=image_image_3
)

spendings_id = canvas.create_text(
    398.0,
    115.0,
    anchor="nw",
    text=0,
    fill="#000000",
    font=("Inter Medium", 24 * -1)
)

canvas.create_text(
    398.0,
    101.0,
    anchor="nw",
    text="Expenses",
    fill="#000000",
    font=("Inter", 13 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    332.0,
    199.0,
    image=image_image_4
)

savings_id =canvas.create_text(
    82.0,
    188.0,
    anchor="nw",
    text=0,
    fill="#000000",
    font=("Inter Medium", 24 * -1)
)
((canvas.itemconfig(savings_id)["text"][4]))
canvas.create_text(
    82.0,
    175.0,
    anchor="nw",
    text="Savings",
    fill="#000000",
    font=("Inter", 13 * -1)
)



canvas.create_text(
    52.0,
    232.0,
    anchor="nw",
    text="Select operations",
    fill="#5465A1",
    font=("Inter", 13, "bold")
)


combobox= ttk.Combobox(
    values=OPTIONS,
    style='TCombobox',  # Możesz dodać styl, jeśli to konieczne
    background="#D9D9D9",
    foreground="#000716"
)
combobox.set("Expenses")
combobox.place(
    x=48.0,
    y=252.0,
    width=222.0,
    height=30.0
)

canvas.create_text(
    52.0,
    291.0,
    anchor="nw",
    text="Name",
    fill="#5465A1",
    font=("Inter", 13 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    156.5,
    323.5,
    image=entry_image_2
)
entry_Name = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_Name.place(
    x=55.0,
    y=306.0,
    width=203.0,
    height=33.0
)

canvas.create_text(
    52.0,
    341.0,
    anchor="nw",
    text="Amount",
    fill="#5465A1",
    font=("Inter", 13 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    156.5,
    373.5,
    image=entry_image_3
)
entry_amount = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_amount.place(
    x=55.0,
    y=356.0,
    width=203.0,
    height=33.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=get_data,
    relief="flat"
)
button_1.place(
    x=43.0,
    y=411.0,
    width=227.0,
    height=38.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    500.0,
    362.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    648.0,
    38.0,
    image=image_image_6
)









window.resizable(False, False)
window.mainloop()
